FROM https://quay.io/kushansewmina/dark-shan-md
RUN git clone https://github.com/kushansewmina1234/DARK-SHAN-MD /root/kushansewmina1234
WORKDIR /root/kushansewmina1234/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]

